/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as signRouteRouteImport } from './routes/(sign)/route'
import { Route as authenicatedRouteRouteImport } from './routes/(authenicated)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as signSignUpRouteImport } from './routes/(sign)/sign-up'
import { Route as signSignInRouteImport } from './routes/(sign)/sign-in'
import { Route as signResetPasswordRouteImport } from './routes/(sign)/reset-password'
import { Route as signForgotPasswordRouteImport } from './routes/(sign)/forgot-password'
import { Route as publicTosRouteImport } from './routes/(public)/tos'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as publicGoodbyeRouteImport } from './routes/(public)/goodbye'
import { Route as authenicatedDashboardRouteImport } from './routes/(authenicated)/dashboard'
import { Route as authenicatedOnboardingRouteRouteImport } from './routes/(authenicated)/onboarding/route'
import { Route as authenicatedOnboardingCompleteRouteImport } from './routes/(authenicated)/onboarding/complete'
import { Route as authenicatedSettingsAccountProfileIndexRouteImport } from './routes/(authenicated)/settings/account/profile/index'
import { Route as authenicatedSettingsAccountPreferencesIndexRouteImport } from './routes/(authenicated)/settings/account/preferences/index'

const signRouteRoute = signRouteRouteImport.update({
  id: '/(sign)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenicatedRouteRoute = authenicatedRouteRouteImport.update({
  id: '/(authenicated)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const signSignUpRoute = signSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => signRouteRoute,
} as any)
const signSignInRoute = signSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => signRouteRoute,
} as any)
const signResetPasswordRoute = signResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => signRouteRoute,
} as any)
const signForgotPasswordRoute = signForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => signRouteRoute,
} as any)
const publicTosRoute = publicTosRouteImport.update({
  id: '/(public)/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/(public)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const publicGoodbyeRoute = publicGoodbyeRouteImport.update({
  id: '/(public)/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const authenicatedDashboardRoute = authenicatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authenicatedRouteRoute,
} as any)
const authenicatedOnboardingRouteRoute =
  authenicatedOnboardingRouteRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => authenicatedRouteRoute,
  } as any)
const authenicatedOnboardingCompleteRoute =
  authenicatedOnboardingCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => authenicatedOnboardingRouteRoute,
  } as any)
const authenicatedSettingsAccountProfileIndexRoute =
  authenicatedSettingsAccountProfileIndexRouteImport.update({
    id: '/settings/account/profile/',
    path: '/settings/account/profile/',
    getParentRoute: () => authenicatedRouteRoute,
  } as any)
const authenicatedSettingsAccountPreferencesIndexRoute =
  authenicatedSettingsAccountPreferencesIndexRouteImport.update({
    id: '/settings/account/preferences/',
    path: '/settings/account/preferences/',
    getParentRoute: () => authenicatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/onboarding': typeof authenicatedOnboardingRouteRouteWithChildren
  '/dashboard': typeof authenicatedDashboardRoute
  '/goodbye': typeof publicGoodbyeRoute
  '/privacy': typeof publicPrivacyRoute
  '/tos': typeof publicTosRoute
  '/forgot-password': typeof signForgotPasswordRoute
  '/reset-password': typeof signResetPasswordRoute
  '/sign-in': typeof signSignInRoute
  '/sign-up': typeof signSignUpRoute
  '/': typeof publicIndexRoute
  '/onboarding/complete': typeof authenicatedOnboardingCompleteRoute
  '/settings/account/preferences': typeof authenicatedSettingsAccountPreferencesIndexRoute
  '/settings/account/profile': typeof authenicatedSettingsAccountProfileIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof authenicatedOnboardingRouteRouteWithChildren
  '/dashboard': typeof authenicatedDashboardRoute
  '/goodbye': typeof publicGoodbyeRoute
  '/privacy': typeof publicPrivacyRoute
  '/tos': typeof publicTosRoute
  '/forgot-password': typeof signForgotPasswordRoute
  '/reset-password': typeof signResetPasswordRoute
  '/sign-in': typeof signSignInRoute
  '/sign-up': typeof signSignUpRoute
  '/': typeof publicIndexRoute
  '/onboarding/complete': typeof authenicatedOnboardingCompleteRoute
  '/settings/account/preferences': typeof authenicatedSettingsAccountPreferencesIndexRoute
  '/settings/account/profile': typeof authenicatedSettingsAccountProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenicated)': typeof authenicatedRouteRouteWithChildren
  '/(sign)': typeof signRouteRouteWithChildren
  '/(authenicated)/onboarding': typeof authenicatedOnboardingRouteRouteWithChildren
  '/(authenicated)/dashboard': typeof authenicatedDashboardRoute
  '/(public)/goodbye': typeof publicGoodbyeRoute
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/tos': typeof publicTosRoute
  '/(sign)/forgot-password': typeof signForgotPasswordRoute
  '/(sign)/reset-password': typeof signResetPasswordRoute
  '/(sign)/sign-in': typeof signSignInRoute
  '/(sign)/sign-up': typeof signSignUpRoute
  '/(public)/': typeof publicIndexRoute
  '/(authenicated)/onboarding/complete': typeof authenicatedOnboardingCompleteRoute
  '/(authenicated)/settings/account/preferences/': typeof authenicatedSettingsAccountPreferencesIndexRoute
  '/(authenicated)/settings/account/profile/': typeof authenicatedSettingsAccountProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboarding'
    | '/dashboard'
    | '/goodbye'
    | '/privacy'
    | '/tos'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/onboarding/complete'
    | '/settings/account/preferences'
    | '/settings/account/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/dashboard'
    | '/goodbye'
    | '/privacy'
    | '/tos'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/onboarding/complete'
    | '/settings/account/preferences'
    | '/settings/account/profile'
  id:
    | '__root__'
    | '/(authenicated)'
    | '/(sign)'
    | '/(authenicated)/onboarding'
    | '/(authenicated)/dashboard'
    | '/(public)/goodbye'
    | '/(public)/privacy'
    | '/(public)/tos'
    | '/(sign)/forgot-password'
    | '/(sign)/reset-password'
    | '/(sign)/sign-in'
    | '/(sign)/sign-up'
    | '/(public)/'
    | '/(authenicated)/onboarding/complete'
    | '/(authenicated)/settings/account/preferences/'
    | '/(authenicated)/settings/account/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenicatedRouteRoute: typeof authenicatedRouteRouteWithChildren
  signRouteRoute: typeof signRouteRouteWithChildren
  publicGoodbyeRoute: typeof publicGoodbyeRoute
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicTosRoute: typeof publicTosRoute
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(sign)': {
      id: '/(sign)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof signRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenicated)': {
      id: '/(authenicated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenicatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(sign)/sign-up': {
      id: '/(sign)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof signSignUpRouteImport
      parentRoute: typeof signRouteRoute
    }
    '/(sign)/sign-in': {
      id: '/(sign)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof signSignInRouteImport
      parentRoute: typeof signRouteRoute
    }
    '/(sign)/reset-password': {
      id: '/(sign)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof signResetPasswordRouteImport
      parentRoute: typeof signRouteRoute
    }
    '/(sign)/forgot-password': {
      id: '/(sign)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof signForgotPasswordRouteImport
      parentRoute: typeof signRouteRoute
    }
    '/(public)/tos': {
      id: '/(public)/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof publicTosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/goodbye': {
      id: '/(public)/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof publicGoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenicated)/dashboard': {
      id: '/(authenicated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenicatedDashboardRouteImport
      parentRoute: typeof authenicatedRouteRoute
    }
    '/(authenicated)/onboarding': {
      id: '/(authenicated)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authenicatedOnboardingRouteRouteImport
      parentRoute: typeof authenicatedRouteRoute
    }
    '/(authenicated)/onboarding/complete': {
      id: '/(authenicated)/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof authenicatedOnboardingCompleteRouteImport
      parentRoute: typeof authenicatedOnboardingRouteRoute
    }
    '/(authenicated)/settings/account/profile/': {
      id: '/(authenicated)/settings/account/profile/'
      path: '/settings/account/profile'
      fullPath: '/settings/account/profile'
      preLoaderRoute: typeof authenicatedSettingsAccountProfileIndexRouteImport
      parentRoute: typeof authenicatedRouteRoute
    }
    '/(authenicated)/settings/account/preferences/': {
      id: '/(authenicated)/settings/account/preferences/'
      path: '/settings/account/preferences'
      fullPath: '/settings/account/preferences'
      preLoaderRoute: typeof authenicatedSettingsAccountPreferencesIndexRouteImport
      parentRoute: typeof authenicatedRouteRoute
    }
  }
}

interface authenicatedOnboardingRouteRouteChildren {
  authenicatedOnboardingCompleteRoute: typeof authenicatedOnboardingCompleteRoute
}

const authenicatedOnboardingRouteRouteChildren: authenicatedOnboardingRouteRouteChildren =
  {
    authenicatedOnboardingCompleteRoute: authenicatedOnboardingCompleteRoute,
  }

const authenicatedOnboardingRouteRouteWithChildren =
  authenicatedOnboardingRouteRoute._addFileChildren(
    authenicatedOnboardingRouteRouteChildren,
  )

interface authenicatedRouteRouteChildren {
  authenicatedOnboardingRouteRoute: typeof authenicatedOnboardingRouteRouteWithChildren
  authenicatedDashboardRoute: typeof authenicatedDashboardRoute
  authenicatedSettingsAccountPreferencesIndexRoute: typeof authenicatedSettingsAccountPreferencesIndexRoute
  authenicatedSettingsAccountProfileIndexRoute: typeof authenicatedSettingsAccountProfileIndexRoute
}

const authenicatedRouteRouteChildren: authenicatedRouteRouteChildren = {
  authenicatedOnboardingRouteRoute:
    authenicatedOnboardingRouteRouteWithChildren,
  authenicatedDashboardRoute: authenicatedDashboardRoute,
  authenicatedSettingsAccountPreferencesIndexRoute:
    authenicatedSettingsAccountPreferencesIndexRoute,
  authenicatedSettingsAccountProfileIndexRoute:
    authenicatedSettingsAccountProfileIndexRoute,
}

const authenicatedRouteRouteWithChildren =
  authenicatedRouteRoute._addFileChildren(authenicatedRouteRouteChildren)

interface signRouteRouteChildren {
  signForgotPasswordRoute: typeof signForgotPasswordRoute
  signResetPasswordRoute: typeof signResetPasswordRoute
  signSignInRoute: typeof signSignInRoute
  signSignUpRoute: typeof signSignUpRoute
}

const signRouteRouteChildren: signRouteRouteChildren = {
  signForgotPasswordRoute: signForgotPasswordRoute,
  signResetPasswordRoute: signResetPasswordRoute,
  signSignInRoute: signSignInRoute,
  signSignUpRoute: signSignUpRoute,
}

const signRouteRouteWithChildren = signRouteRoute._addFileChildren(
  signRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenicatedRouteRoute: authenicatedRouteRouteWithChildren,
  signRouteRoute: signRouteRouteWithChildren,
  publicGoodbyeRoute: publicGoodbyeRoute,
  publicPrivacyRoute: publicPrivacyRoute,
  publicTosRoute: publicTosRoute,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
